### ISSUE TITLE
Validate cluster availability for Ops Kamloops Lab

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#53] opened 2019-11-07 20:28 UTC
- [ ]  Storage Pool Configuration (netapp-block-standard, netapp-file-standard)
- [ ]  Registry Configuration with storage (S3? NFS?)
- [ ]  Certificates for external endpoints (may need procurement)
- [ ]  Service Catalog
    - [ ]  *Samples* operator (looks like it might keep openshift namespace images and templates up to date)
    - [ ]  *Template Service Broker*
    - [ ]  *Ansible Broker* (Do we want to install this as well?)
- [ ]  Cluster Logging
- [ ]  Cluster Monitoring
- [ ]  Cluster Metering
- [ ]  Restricted cluster RBAC base
    - [ ]  Cluster admins, cluster viewers
    - [ ]  BCDevEx service Account (and oc "as" permissions)
    - [ ]  restricted project/namespace creation
    - [ ]  ...

**Comment by jefkel** [comment] 2020-03-11 17:38
Review whether this is duplicated in automation epic #173

**Comment by tosazuwa** [comment] 2020-03-30 20:06
Closing. Duplicate of #173

**Closed as completed by tosazuwa** 2020-03-30 20:06 UTC
