### ISSUE TITLE
Testing of F5 components for Kamloops Lab

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#152] opened 2020-01-20 20:02 UTC
- [ ] Create Test Plans

**Comment by DanDeane** [comment] 2020-02-20 18:32
adding @sbarre-esit

**Comment by StevenBarre** [comment] 2020-02-21 00:22
@jefkel Any suggestions for test plans for this? What features are you looking for?

**Comment by jefkel** [comment] 2020-02-26 17:43
Duplicate of issue #49
Closing

**Closed as completed by jefkel** 2020-02-26 17:43 UTC
Labels: site/kamloops, team/DXC
