### ISSUE TITLE
NetApp NFS Permissions vendor bug

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#186] opened 2020-03-30 20:09 UTC
Working with NetApp support to resolve an ongoing bug in the NFS Permissions when Trident is provisioning Persistent Volumes

Vendor case ID 2008214274

After much back and forth between NetApp support and Red Hat support, the root issue appears to be that Trident CSI sidecar is not setting the fsType to none or blank, causing the default of ext4 to be used. On a remount, volumes with a fsType set and RWO get pased to code to chmod -R which is failing. Action appears to be on NetApps hands to fix Trident.

- https://github.com/kubernetes/kubernetes/blob/056374d9c8b8e43745d8a97f82981f886702cef8/pkg/volume/csi/csi_mounter.go#L376
- https://bugzilla.redhat.com/show_bug.cgi?id=1809174
- https://github.com/kubernetes-csi/external-provisioner/blob/efcaee79e47446e38910a3c1a024824387fcf235/pkg/controller/controller.go#L119

Had a call with NetApp to figure out why they couldn't reproduce. It was related to Security Context Constraints. They can now hopefully reproduce the errors I'm having.

They will be fixing the `fsType` bug hopefully in the 20.04 release of Trident at the end of April.

A workaround for now seems to be to open up the SCC in a namespace.

```bash
oc adm policy add-scc-to-group anyuid system:serviceaccounts:pvc-test
```

**Comment by jefkel** [comment] 2020-03-30 20:12
Blocked pending vendor bugfix

**Comment by StevenBarre** [comment] 2020-04-03 16:14
Vendor is somehow still unable to reproduce. sigh.

I have found a better workaround. Setting the NFS export policy to `-anon 0` allows root to manage the permissions on the filesystem and stops the "operation not permitted" errors without needing the anyuid scc.

I think this is at least a good enough fix for us to move forward on and shouldn't block further efforts to build clusters.

**Comment by StevenBarre** [comment] 2020-04-15 19:30
Followed up again with the vendor after no response since Apr 3rd.

**Comment by StevenBarre** [comment] 2020-05-06 21:21
Call with vendor on Apr 29th. We agreed on a path forward. I did some more debugging and came up with a simpler way to reproduce showing it is related to the permissions of the folder being mounted in the container image.

Response on Tues saying "that looks like it should work". Storage team is going to escalate.

**Comment by StevenBarre** [comment] 2020-05-14 20:25
When Trident provisions a volume it assigns the Trident created export policy to that volume. When Trident provisions the qtree it assigns the vservers default export policy to the qtree. 

So our options to work around the applyFSGroups issue is to

1) set default export policy to Superuser Security Type = Any

CLAB_SVM1::> vserver export-policy rule modify  -policyname default -ruleindex 1 -superuser any

2) Tell trident to use the trident created policy for qtrees

Update the backend.json with

    "defaults": { "exportPolicy": "trident_qtree_pool_export_policy"}

3) set the default export policy User ID To Which Anonymous Users Are Mapped to zero or root

CLAB_SVM1::> vserver export-policy rule modify  -policyname default -ruleindex 1 -anon 0

I'll likely go with 1 or 2 as they seem more secure as a workaround. I've tested 1 and 3.

We will wait for https://github.com/kubernetes-csi/external-provisioner/pull/400 to get merged and then get a Trident release making use of it. Then we won’t be triggering the applyFSGroup() code path at all.

**Comment by StevenBarre** [comment] 2020-05-15 18:24
Trident issue to track integrating the sidecar https://github.com/NetApp/trident/issues/402

**Comment by mitovskaol** [comment] 2020-06-04 17:38
Need time to automate the workaround.

**Comment by StevenBarre** [comment] 2020-06-16 17:42
https://github.com/bcgov-c/platform-ops/pull/246

**Closed as completed** 2020-06-17 22:18 UTC
Labels: bug, tech/storage, team/DXC
