### ISSUE TITLE
Configure NetApp devices for Kamloops Lab

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#50] opened 2019-11-07 20:28 UTC
- [x] Establish Cluster Name - MCS-KLAB-NETAPP
- [x] Order gear under #47
- [x] Plan network design
- [x] Reserve IP Addresses and DNS Names from Network Team
- [x] Storage Team - Download latest ONTAP firmware and install and configure
  - [x] Dan to deploy VMs
  - [x] Submit request for SMTP to Infrastructure Group
  - [x] Configure AutoSupport for HTTPS  (Firewall requests)
  - [x] Configure Timezone and NTP
  - [x] Create SVM for Trident/OpenShift
  - [x] Create SVM for CORP Login
  - [x] Create Aggregates on both nodes
  - [x] Configure Aggregate Delegation
  - [x] Disable FSID
  - [x] Configure NFS Protocol and NFS Data LIF
  - [x] Configure iSCSI Protocol and iSCSI Data LIFs on each node
  - [x] Add cluster to Unified Manager
- [x] Setup Trident on the cluster and test
- [x] Apply licence

**Comment by jefkel** [comment] 2020-01-21 18:47
Removed block of ordering licenses as these tasks can be done using the trial licenses, with the expectation that we will destroy/re-deploy once we have appropriate licenses.

**Comment by tosazuwa** [comment] 2020-01-29 20:08
Virtual Servers and SAN for the KLAB and CLAB storage now moving forward. NetApp Virtuals to be deployed in LAB (Calgary & Kamloops) and handed off to the Storage team by Feb 7th 2020

**Comment by tosazuwa** [comment] 2020-01-29 20:09
@sbarre-esit @DanDeane , can you check off any of the activities listed above?

**Comment by DanDeane** [comment] 2020-02-04 17:58
required vlans are in place as of last night, firewall rules go in tonight.

**Comment by DanDeane** [comment] 2020-02-07 14:48
Kamloops Lab NetApp clusters deployed yesterday and handed over to our storage team to configure.

**Comment by StevenBarre** [comment] 2020-02-21 00:16
Testing of Trident and the two storage classes. Some work was needed to get iscsi working properly on RHCOS.

Now testing an issue with file volumes having permissions issues. Emailed NetApp support with details.

**Comment by StevenBarre** [comment] 2020-02-21 00:18
Storage team applied the license today!

**Comment by StevenBarre** [comment] 2020-02-27 23:55
Working with Red Hat on NFS permissions issue. Still not working.

**Comment by StevenBarre** [comment] 2020-03-09 17:08
After much back and forth between NetApp support and Red Hat support, the root issue appears to be that Trident CSI sidecar is not setting the `fsType` to none or blank, causing the default of ext4 to be used. On a remount, volumes with a `fsType` set and RWO get pased to code to `chmod -R` which is failing. Action appears to be on NetApps hands to fix Trident.

- https://github.com/kubernetes/kubernetes/blob/056374d9c8b8e43745d8a97f82981f886702cef8/pkg/volume/csi/csi_mounter.go#L376
- https://bugzilla.redhat.com/show_bug.cgi?id=1809174
- https://github.com/kubernetes-csi/external-provisioner/blob/efcaee79e47446e38910a3c1a024824387fcf235/pkg/controller/controller.go#L119

Moving to Blocked while the vendors sort this out and get us a patch.

**Comment by StevenBarre** [comment] 2020-03-18 19:10
Had a call with NetApp today to figure out why they couldn't reproduce. It was related to Security Context Constraints. They can now hopefully reproduce the errors I'm having.

They will be fixing the `fsType` bug hopefully in the 20.04 release of Trident at the end of April.

A workaround for now seems to be to open up the SCC in a namespace.

```bash
oc adm policy add-scc-to-group anyuid system:serviceaccounts:pvc-test
```

**Comment by StevenBarre** [comment] 2020-03-30 20:11
Completed except for issue tracked in #186

**Closed as completed by StevenBarre** 2020-03-30 20:11 UTC
Labels: site/kamloops, env/lab, tech/storage, team/DXC, Blocked
